
NEW_DIR_TIMR = "2019.10-2019.03"


MEETING_COUNT = 107
MEETING_THEME = "Emergency Handling"
MEETING_DATE = "2018.10.12"
TableTopic = "Xin Feng, Ronaldo, Dongchen Tang, Jamine, Robin"
BestTableTopicSpeech = "Ronaldo"
BestPreparedSpeech = ""
BestEvaluator = ""
PERPARED_SPEACKERS = [{
        "project_rank": "L1-2",
        "people_name": "Jenny Yu",
        "project_name": "Happiness"
    },
    {
        "project_rank": "L1-2",
        "people_name": "Michelle Wang",
        "project_name": "Dancing with Anxiety"
    },
    {
        "project_rank": "",
        "people_name": "",
        "project_name": ""
    },
    {
        "project_rank": "",
        "people_name": "",
        "project_name": ""
    },
    {
        "project_rank": "",
        "people_name": "",
        "project_name": ""
    },
    {
        "project_rank": "",
        "people_name": "",
        "project_name": ""
    }
]
ROLE_TAKERS = {
    "TMD": "Hong Wang",
    "TTM": "Yayun Sun",
    "GE": "Dongchen Tang",
    "IE": "Jun Liu, Ronaldo Huang",
    "Grammarian": "Fang Yao",
    "Timer": "Huihui Jiang",
    "Ah-counter": "Jenny Yu"
}
AttendanceName = "Dongchen Tang,Yi Fang,Taowen Zhang,Elvis Jiang,Jun Liu,Wujie Zhang,Xin Feng,Yayun Sun, Anne,Michelle Wang,Jenny Yu,Hong Wang,Huihui Jiang,Qingzhen Deng"







#  you don't need to change the value.

md_path_dir = "eshtmc.github.io/education/meetings/{0}/".format(NEW_DIR_TIMR)

INDEX_ADD ="""
### {0}
[attendance](https://eshtmc.github.io/education/meetings/{0}/attendance.html)
[best-awards](https://eshtmc.github.io/education/meetings/{0}/best-awards)
[role-takers](https://eshtmc.github.io/education/meetings/{0}/role-takers)
[speakers](https://eshtmc.github.io/education/meetings/{0}/speakers)
""".format(NEW_DIR_TIMR)



New_Table="""<h1>Attendance</h1>
<table class="table table-condensed table-bordered">
<tr><th>Name</th></tr>
<tr><th>Jenny Yu</th></tr>
<tr><th>Huihui Jiang</th></tr>
<tr><th>Jony Zheng</th></tr>
<tr><th>Michelle Wang</th></tr>
<tr><th>Dongchen Tang</th></tr>
<tr><th>Michelle Hua</th></tr>
<tr><th>Jane Gong</th></tr>
<tr><th>Taowen Zhang</th></tr>
<tr><th>Yi Fang</th></tr>
<tr><th>Hongyu Qi</th></tr>
<tr><th>Qingzhen Deng</th></tr>
<tr><th>Siyuan Jia</th></tr>
<tr><th>Michelle Jin</th></tr>
<tr><th>Alice Huang</th></tr>
<tr><th>Xin Feng</th></tr>
<tr><th>Sarah Zhang</th></tr>
<tr><th>Wujie Zhang</th></tr>
<tr><th>Yao Fang</th></tr>
<tr><th>Elvis Jiang</th></tr>
<tr><th>Nrapendra Singh</th></tr>
<tr><th>Hong Wang</th></tr>
<tr><th>Jun Liu</th></tr>
<tr><th>Total</th></tr>
</table>      
"""



HTML_ATTENDANCE_head="""
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>eshtmc.github.io | database of eshtmc</title>
<meta name="generator" content="Jekyll v3.7.4" />
<meta property="og:title" content="eshtmc.github.io" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="database of eshtmc" />
<meta property="og:description" content="database of eshtmc" />
<link rel="canonical" href="https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html" />
<meta property="og:url" content="https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html" />
<meta property="og:site_name" content="eshtmc.github.io" />
<script type="application/ld+json">
{"@type":"WebPage","headline":"eshtmc.github.io","url":"https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html","description":"database of eshtmc","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <link rel="stylesheet" href="/assets/css/style.css?v=86d9adce21742320d63342ba5413bdb59e243364">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">eshtmc.github.io</h1>
      <h2 class="project-tagline">database of eshtmc</h2>


    </section>

    <section class="main-content">
      <h4 id="home"><a href="https://eshtmc.github.io/">Home</a></h4>
      
"""

HTML_ATTENDANCE_end ="""

      <footer class="site-footer">

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </section>


  </body>
</html>




"""


